networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - temp.env
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        [
        "CMD-SHELL",
        "mariadb --protocol=socket --socket=/run/mysqld/mysqld.sock -u root -p\"$(cat /run/secrets/db_root_password)\" -e \"SELECT 1\" >/dev/null 2>&1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - inception
    secrets:
      - db_root_password
      - db_health_user
      - db_health_password
      - wp_db_name
      - wp_db_password
      - wp_db_user

secrets:
  db_root_password:
    file: ../secrets/db_root_password
  db_health_user:
    file: ../secrets/db_health_user
  db_health_password:
    file: ../secrets/db_health_password
  wp_db_name:
    file: ../secrets/wp_db_name
  wp_db_user:
    file: ../secrets/wp_db_user
  wp_db_password:
    file: ../secrets/wp_db_password

volumes:
  mariadb_data:
