CREATE DATABASE IF NOT EXISTS `${MDB_DATABASE}`;

CREATE USER IF NOT EXISTS '${MDB_USER}'@'%' IDENTIFIED BY '${MDB_PASSWORD}';
GRANT ALL PRIVILEGES ON `${MDB_DATABASE}`.* TO '${MDB_USER}'@'%';

FLUSH PRIVILEGES;